FROM python:3
 
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code

COPY ../requirements.txt .
ADD . /code/

RUN \   
    pip install -r requirements.txt

EXPOSE 8000
CMD ["python", "bot_app/bot_app.py"]
